version: "3.8"

services:
  # web:
  #   image: ecfatum/property-mgt-api:dev
  #   ports:
  #     - "8090:3000"
  #   networks:
  #     - app-network
  #   container_name: asset911-web
  #   env_file:
  #     - .web.env
  #   volumes:
  #     - .web.env:/app/.env
  #   depends_on:
  #     - api


  api:
    image: ecfatum/property-mgt-api:dev
    ports:
      - "8035:5000"
    networks:
      - app-network
    container_name: property-mgt-api
    env_file:
      - .env
    volumes:
      - .env:/app/.env

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  static_volume: