name: deploy-api-prod

on:
  push:
    branches:
      - master
      - prod
jobs:
  build:
    name: Deploy image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t ecfatum/property-mgt-api:prod .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push ecfatum/property-mgt-api:prod